name: SamplePlugin
main: net.craftstars.sampleplugin.SamplePlugin
version: 1.0
authors:
  - Plutonium239
commands:
  sampleplugin:
    description: The only command included with SamplePlugin
    aliases:
      - /samplepluginalias
    usage: |
           /<command> [invalid]
           Example: /<command> - Runs SamplePlugin command.
           Example: /<command> invalid - Imitates invalid command.